=== openimagingdata/openimagingdata.org/schemas/observation_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Observation",
  "definitions": {
    "Observation": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^\\$": {
          "description": "Any property starting with $ is reserved for notations and extensions",
          "tsType": "any"
        }
      },
      "properties": {
        "resourceType": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "code": {
          "$ref": "#/definitions/SystemCode"
        },
        "bodySite": {
          "$ref": "#/definitions/BodySite"
        },
        "component": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Component"
          }
        }
      },
      "required": ["resourceType", "id", "code", "component"],
      "title": "Observation"
    },
    "BodySite": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "$ref": "#/definitions/SystemCodeList"
        }
      },
      "required": ["code"],
      "title": "BodySite"
    },
    "SystemCodeList": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "coding": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SystemCode"
          },
          "minItems": 1
        }
      },
      "required": ["coding"],
      "title": "SystemCodeList"
    },
    "SystemCode": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "system": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": ["https"]
        },
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "required": ["system", "code"],
      "title": "SystemCode"
    },
    "Component": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "$ref": "#/definitions/SystemCodeList"
        },
        "valueCodeableConcept": {
          "$ref": "#/definitions/SystemCodeList"
        },
        "valueString": {
          "type": "string"
        },
        "valueInteger": {
          "type": "integer"
        },
        "valueFloat": {
          "type": "string",
          "format": "float"
        }
      },
      "required": ["code"],
      "oneOf": [
        {
          "required": ["valueCodeableConcept"]
        },
        {
          "required": ["valueString"]
        },
        {
          "required": ["valueInteger"]
        }
      ],
      "title": "Component"
    }
  }
}

=== openimagingdata/openimagingdata.org/schemas/sample_observation_min.json
{
  "$schema": "./observation_schema.json",
  "resourceType": "Observation",
  "id": "bdfa505a-3a82-4bdd-b987-e7f75af9f438",
  "code": {
    "system": "https://radelement.org",
    "code": "RDES47"
  },
  "component": [
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE256"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE256.2"
          }
        ]
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE257"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE257.2"
          }
        ]
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE258"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE258.1"
          }
        ]
      }
    },
    {
        "code": {
          "coding": [
            {
              "system": "https://radelement.org",
              "code": "RDE637"
            }
          ]
        },
        "valueString": "42.595, 20.658, 59.874, 20.658"
      },
      {
        "code": {
          "coding": [
            {
              "system": "https://radelement.org",
              "code": "RDE714"
            }
          ]
        },
        "valueInteger": 2
      }
    ]
}

=== openimagingdata/openimagingdata.org/schemas/sample_observation.json
{
  "$schema": "./observation_schema.json",
  "resourceType": "Observation",
  "id": "28d99870-ace5-46bd-8742-1d9a6d1796fc",
  "code": {
    "system": "https://radelement.org",
    "code": "RDES47",
    "display": "Stener Lesion"
  },
  "bodySite": {
    "code": {
      "coding": [
        {
          "system": "https://www.anatomiclocations.org/",
          "code": "RID2035",
          "display": "ulnar collateral ligament of elbow"
        }
      ]
    }
  },
  "component": [
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE256",
            "display": "Classification"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE256.2",
            "display": "full-thickness tear"
          }
        ]
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE257",
            "display": "Status"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE257.2",
            "display": "abnormal"
          }
        ]
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE258",
            "display": "Presence"
          }
        ]
      },
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE258.1",
            "display": "present"
          }
        ]
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE637",
            "display": "femur length coordinates"
          }
        ]
      },
      "valueString": "42.595, 20.658, 59.874, 20.658"
    },
    {
      "code": {
        "coding": [
          {
            "system": "https://radelement.org",
            "code": "RDE714",
            "display": "number of rib fractures"
          }
        ]
      },
      "valueInteger": 2
    }
  ]
}
